# Generated by Django 6.0.3 on 2026-04-08 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('DOS', 'Director of Study')], default='DOS', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.school')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hours_studied', models.IntegerField(default=20)),
                ('attendance', models.IntegerField(default=90)),
                ('sleep_hours', models.IntegerField(default=7)),
                ('previous_scores', models.IntegerField(default=70)),
                ('tutoring_sessions', models.IntegerField(default=0)),
                ('physical_activity', models.IntegerField(default=3)),
                ('parental_involvement', models.CharField(default='Medium', max_length=20)),
                ('access_to_resources', models.CharField(default='Medium', max_length=20)),
                ('extracurricular_activities', models.CharField(default='No', max_length=3)),
                ('motivation_level', models.CharField(default='Medium', max_length=20)),
                ('internet_access', models.CharField(default='Yes', max_length=3)),
                ('family_income', models.CharField(default='Medium', max_length=20)),
                ('teacher_quality', models.CharField(default='Medium', max_length=20)),
                ('school_type', models.CharField(default='Public', max_length=20)),
                ('peer_influence', models.CharField(default='Neutral', max_length=20)),
                ('learning_disabilities', models.CharField(default='No', max_length=3)),
                ('parental_education_level', models.CharField(default='College', max_length=30)),
                ('distance_from_home', models.CharField(default='Near', max_length=20)),
                ('gender', models.CharField(default='Male', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.school')),
            ],
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_mark', models.FloatField(default=50.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analytics.school')),
            ],
        ),
    ]
