# Generated by Django 6.0.3 on 2026-04-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
